version: '3'
services:
  mongodb:
    container_name: alinecampos_mongodb
    image: mongo
    ports:
    - "27017:27017"
    volumes:  
    - './data:/data/db'
  nodejs:
    container_name: alinecampos_nodejs
    build: ./
    ports:
     - "3000:3000"
    volumes:
      - ./server/:/home/app
      - /home/app/node_modules
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017